spring:
    config:
        import: optional:file:src/main/resources/.env[.properties]
    application:
        name: app

server:
    port: ${SERVER_PORT:8080}
    error:
        whitelabel:
            enabled: false 

config:
    environment: ${ENVIRONMENT:dev}