spring:
    config:
        import: optional:file:src/main/resources/.env[.properties]
    application:
        name: app
    datasource:
        url: ${DB_HOST}
        username: ${DB_USERNAME}
        password: ${DB_PASSWORD}
        driver-class-name: org.postgresql.Driver
    jpa:
        properties:
            hibernate:
                default_schema: ${ENVIRONMENT:dev}
                dialect: org.hibernate.dialect.PostgreSQLDialect
                format_sql: true
        hibernate:
            ddl-auto: update
        show-sql: true

server:
    port: ${SERVER_PORT:8080}
    error:
        whitelabel:
            enabled: false 

config:
    environment: ${ENVIRONMENT:dev}