spring:
    config:
        import: optional:file:src/main/resources/.env[.properties]
    application:
        name: app
    datasource:
        url: ${DB_HOST:jdbc:postgresql://localhost:5432/defaultdb}
        username: ${DB_USERNAME}
        password: ${DB_PASSWORD}
        driver-class-name: org.postgresql.Driver
    jpa:
        properties:
            hibernate:
                default_schema: ${ENVIRONMENT:dev}
                dialect: org.hibernate.dialect.PostgreSQLDialect
                format_sql: true
        hibernate:
            ddl-auto: update
        show-sql: true
    autoconfigure:
        exclude:
            - org.springframework.boot.autoconfigure.data.redis.RedisAutoConfiguration
            - org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration
            - org.springframework.boot.autoconfigure.thymeleaf.ThymeleafAutoConfiguration


server:
    port: ${SERVER_PORT:8080}
    error:
        whitelabel:
            enabled: false

env:
    environment: ${ENVIRONMENT:dev}
    client_id: ${CLIENT_ID}
    client_secret: ${CLIENT_SECRET}
    redirect_url: ${REDIRECT_URL}
